### ISSUE TITLE
[v0.1.0 regression] compilation fails with GOOS=freebsd

### ISSUE THREAD

**Issue by AkihiroSuda** [ipfs/go-ipfs-files#47]
go-ipfs-files@v0.1.0 can't be compiled for `GOOS=freebsd`:
```
$ GOOS=freebsd go build
# github.com/ipfs/go-ipfs-files
./filewriter.go:25:13: undefined: createNewFile
./filewriter.go:30:10: cannot assign error to err in multiple assignment
./filewriter.go:47:6: undefined: isValidFilename
```

v0.0.9 was compilable.

Go version: 1.17.6

**Comment by aschmahmann** [comment]
@AkihiroSuda support for freebsd is best effort (we don't have CI support for it and none of the maintainers use freebsd which makes it not something we can maintain), however we're certainly open to clean PRs that get things working for freebsd.

#48 likely fixes the issue, although I haven't tested it (see above about the lack of support). If you could verify that things work on your end we can merge the PR and cut a patch release.
