### ISSUE TITLE
Handle multipart files without directories

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-files#5]
js-ipfs sends multipart requests _without_ directories. That is, it just sends a stream of files and expects the server to infer where it needs new directories.

**Comment by Stebalien** [comment]
I'm pretty sure this only ever worked by coincidence. However, we still need to fix it.

**Comment by magik6k** [comment]
Do I just run `jsipfs add` with ipfs_path pointing to a go-ipfs repo with running daemon to reproduce?

**Comment by Stebalien** [comment]
Yes. I created a fix (https://github.com/ipfs/go-ipfs-files/pull/6) but it's a moderately opinionated one so feel free to redo/rework it to be less invasive.
